# Generated by Django 3.2.6 on 2021-12-01 04:48

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='작성자')),
                ('contents', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종수정일')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth', models.IntegerField(default=0, null=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=200, null=True, verbose_name='영어카테고리')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KingTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yt.tag')),
                ('address_name', models.CharField(default='', max_length=200)),
                ('parentTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childTag', to='yt.tag')),
            ],
            bases=('yt.tag',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modify_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.boardmember', verbose_name='작성자')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.board')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chan_id', models.CharField(max_length=200)),
                ('chan_keyword', django_mysql.models.ListCharField(models.CharField(max_length=200), default=[], max_length=6030, size=30)),
                ('chan_img', models.CharField(default='', max_length=200)),
                ('chan_title', models.CharField(default='', max_length=200)),
                ('chan_description', models.TextField(default='')),
                ('subscription_count', models.IntegerField(default=-1)),
                ('chan_viewCount', models.BigIntegerField(default=-1)),
                ('chan_videoThumb', django_mysql.models.ListCharField(models.CharField(max_length=300), default=[], max_length=1505, size=5)),
                ('tag', models.ManyToManyField(related_name='tagged', to='yt.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.category', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yt.boardmember', verbose_name='작성자'),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='yt.tag')),
                ('kingtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='yt.kingtag')),
            ],
        ),
    ]
