# Generated by Django 3.2.6 on 2021-12-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='chan_description',
        ),
    ]
