# Generated by Django 3.2.6 on 2021-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0002_remove_channel_chan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='chan_description',
            field=models.TextField(default=''),
        ),
    ]
