# Generated by Django 3.2.6 on 2022-07-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0004_channel_chan_videotitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='chan_videoTitle',
        ),
    ]
