# Generated by Django 3.2.6 on 2022-07-19 06:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0005_remove_channel_chan_videotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='chan_videoTitle',
            field=django_mysql.models.ListTextField(models.CharField(max_length=300), default=[], size=5),
        ),
    ]
