# Generated by Django 3.2.6 on 2022-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0006_channel_chan_videotitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=300)),
                ('tag', models.ManyToManyField(related_name='videos', to='yt.Tag')),
            ],
        ),
    ]
