# Generated by Django 3.2.6 on 2022-07-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0008_channel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='video',
        ),
    ]
