# Generated by Django 3.2.6 on 2022-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0009_remove_channel_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToFIx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chan_id', models.CharField(max_length=200)),
                ('errorType', models.CharField(max_length=200)),
            ],
        ),
    ]
