# Generated by Django 3.2.6 on 2022-07-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0010_tofix'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='video',
            field=models.ManyToManyField(related_name='channel', to='yt.Video'),
        ),
    ]
