# Generated by Django 3.2.6 on 2022-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0011_channel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
