# Generated by Django 3.2.6 on 2022-07-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0012_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
