# Generated by Django 3.2.6 on 2022-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0013_auto_20220722_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('thumbnail', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=300)),
                ('video_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('tag', models.ManyToManyField(related_name='videos', to='yt.Tag')),
            ],
        ),
    ]
