# Generated by Django 3.2.6 on 2022-08-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0015_channel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingtag',
            name='parentTag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='childTag', to='yt.tag'),
        ),
    ]
